const RESTART_GAME = "RESTART_GAME";
const UPDATE_CELL_ON_BOARD = "UPDATE_CELL_ON_BOARD";
const SET_GAME_INACTIVE = "SET_GAME_INACTIVE";
const GET_NEXT_PLAYER = "GET_NEXT_PLAYER";

export { 
    RESTART_GAME, 
    UPDATE_CELL_ON_BOARD, 
    SET_GAME_INACTIVE, 
    GET_NEXT_PLAYER,
};
