const RESTART_GAME = "RESTART_GAME";
const UPDATE_CELL_ON_BOARD = "UPDATE_CELL_ON_BOARD";
const SET_PLAYER_WIN_STATUS = "SET_PLAYER_WIN_STATUS";
const SET_CAT_STATUS = "SET_CAT_STATUS";
const GET_NEXT_PLAYER = "GET_NEXT_PLAYER";

export { 
    RESTART_GAME, 
    UPDATE_CELL_ON_BOARD, 
    SET_PLAYER_WIN_STATUS, 
    SET_CAT_STATUS,
    GET_NEXT_PLAYER
};
