const RESTART_GAME = "RESTART_GAME";
const UPDATE_GRID_ELEMENT = "UPDATE_GRID_ELEMENT";
const SET_GAME_INACTIVE = "SET_GAME_INACTIVE";
const GET_NEXT_PLAYER = "GET_NEXT_PLAYER";

export { 
    RESTART_GAME, 
    UPDATE_GRID_ELEMENT, 
    SET_GAME_INACTIVE, 
    GET_NEXT_PLAYER,
};
