const UPDATE_GRID_ELEMENT = "UPDATE_GRID_ELEMENT";
const SET_IS_GAME_ACTIVE = "SET_IS_GAME_ACTIVE";
const SET_CURRENT_PLAYER = "SET_CURRENT_PLAYER";

export { UPDATE_GRID_ELEMENT, SET_IS_GAME_ACTIVE, SET_CURRENT_PLAYER };
